# Generated by Django 2.0.7 on 2018-08-08 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectpagegalleryimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpage',
            name='github',
            field=models.CharField(help_text='Make sure to include http protocol or else the link will be relative.', max_length=250),
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='project_url',
            field=models.CharField(help_text='Make sure to include http protocol or else the link will be relative.', max_length=250),
        ),
    ]
