# Generated by Django 2.0.7 on 2018-10-25 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20180808_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpage',
            name='github',
            field=models.CharField(blank=True, help_text='Make sure to include http protocol or else the link will be relative.', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='project_url',
            field=models.CharField(blank=True, help_text='Make sure to include http protocol or else the link will be relative.', max_length=250, null=True),
        ),
    ]
