# Generated by Django 2.0.7 on 2018-07-26 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='skill1',
            field=models.CharField(blank=True, help_text='Title to display above the promo copy', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='skill2',
            field=models.CharField(blank=True, help_text='Title to display above the promo copy', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='skill3',
            field=models.CharField(blank=True, help_text='Title to display above the promo copy', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='skill4',
            field=models.CharField(blank=True, help_text='Title to display above the promo copy', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='skill5',
            field=models.CharField(blank=True, help_text='Title to display above the promo copy', max_length=255, null=True),
        ),
    ]
