# Generated by Django 2.0.7 on 2018-08-02 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20180801_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='skill_6',
            field=models.CharField(blank=True, help_text='A techincal skill i.e. Python', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='skill_6_percentage',
            field=models.IntegerField(blank=True, help_text='A percentage of mastery i.e. 90 percent. Just write the number not the percentage sign.', null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='skill_7',
            field=models.CharField(blank=True, help_text='A techincal skill i.e. Python', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='skill_7_percentage',
            field=models.IntegerField(blank=True, help_text='A percentage of mastery i.e. 90 percent. Just write the number not the percentage sign.', null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='skill_8',
            field=models.CharField(blank=True, help_text='A techincal skill i.e. Python', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='skill_8_percentage',
            field=models.IntegerField(blank=True, help_text='A percentage of mastery i.e. 90 percent. Just write the number not the percentage sign.', null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='skill_9',
            field=models.CharField(blank=True, help_text='A techincal skill i.e. Python', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='skill_9_percentage',
            field=models.IntegerField(blank=True, help_text='A percentage of mastery i.e. 90 percent. Just write the number not the percentage sign.', null=True),
        ),
    ]
