# Generated by Django 2.0.7 on 2018-08-03 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20180802_1645'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='hero_cta',
            new_name='hero_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='email',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_cta_link',
        ),
    ]
