# Generated by Django 2.0.7 on 2018-10-25 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20181025_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='skill_1',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='skill_1_percentage',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='skill_2',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='skill_2_percentage',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='skill_3',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='skill_3_percentage',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='skill_4',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='skill_4_percentage',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='skill_5',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='skill_5_percentage',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='skill_6',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='skill_6_percentage',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='skill_7',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='skill_7_percentage',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='skill_8',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='skill_8_percentage',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='skill_9',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='skill_9_percentage',
        ),
    ]
