# Generated by Django 2.0.7 on 2019-02-19 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20190219_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='featured_section_1',
            field=models.ForeignKey(blank=True, help_text='First featured section for\n            the homepage. Will display up tothree child names.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page', verbose_name='Featured section 1'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='featured_section_2',
            field=models.ForeignKey(blank=True, help_text='First featured section for\n            the homepage. Will display up to three child names.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page', verbose_name='Featured section 1'),
        ),
        migrations.AlterField(
            model_name='skills',
            name='percentage',
            field=models.IntegerField(blank=True, help_text='A percentage of mastery\n            i.e. 90 percent. Just write the number not the percentage sign.', null=True),
        ),
        migrations.AlterField(
            model_name='standardpage',
            name='image',
            field=models.ForeignKey(blank=True, help_text='Landscape mode only;\n            horizontal width between 1000px and 3000px', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
